name: Download Filters

on:
  schedule:
  - cron: "0 2 * * *"
  # For manual run builds
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Build Allowlist
        run: TLS=insecure node src/cli.js -c examples/whitelist/configuration.json -o ./optimized/whitelist.txt

      - name: Build DNS Filter
        run: TLS=insecure node src/cli.js -c examples/sdn/configuration.json -o ./optimized/filter.txt

      - name: Download and transform Adguard Filters
        run: |
          (curl -s https://filters.adtidy.org/ios/filters/15_optimized.txt | grep -v "\*" | grep -v "^@@") > ./optimized/dns_optimized.txt
          (curl -s "https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exceptions.txt" | \sed 's/^@@||//g; s/^@@|//g; s/|$//g; /^!/!s/^/||/') > ./optimized/dns_whitelist.txt

      - name: Build Adguard Optimized
        run: |             
          {
            curl -s https://filters.adtidy.org/ios/filters/101_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/2_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/3_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/4_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/11_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/14_optimized.txt
            curl -s https://raw.githubusercontent.com/liamengland1/miscfilters/refs/heads/master/antipaywall.txt | sed '/^! Bloomberg (bloomberg\.com)$/,/^$/d; /##+js(trusted/d'
            curl -s https://bpc-filter-proxy.wmailrelayb8d890.workers.dev | grep -iv "bloomberg\|##+js(trusted"
          } > ./optimized/adguard.txt

      - name: Build EasyList Optimized
        run: |             
          {
            curl -s https://filters.adtidy.org/ios/filters/101_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/118_optimized.txt
            curl -s https://filters.adtidy.org/ios/filters/122_optimized.txt
            curl -s https://raw.githubusercontent.com/liamengland1/miscfilters/refs/heads/master/antipaywall.txt | sed '/^! Bloomberg (bloomberg\.com)$/,/^$/d'
            curl -s https://bpc-filter-proxy.wmailrelayb8d890.workers.dev | grep -iv "bloomberg\|##+js(trusted"
          } > ./optimized/easylist.txt

      - name: Build Scriptlets
        run: |              
          {
            curl -s https://filters.adtidy.org/ios/filters/2.txt | sed -n '/! START: Youtube whitescreen fix/,/! END: Youtube whitescreen fix/p'
            curl -s https://filters.adtidy.org/ios/filters/5.txt | sed -n '/! YouTube ads/,/! Allowlist/p'
            curl -s https://filters.adtidy.org/ios/filters/2.txt | sed -n '/! START: Ad-Shield ad reinsertion/,/! END: Ad-Shield ad reinsertion/p'
            } > ./optimized/scriptlets.txt 

      - name: Build uBlock
        run: |              
          {
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/filters.min.txt | sed '/www\.youtube\.com/d'
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/filters-general.txt
            # curl -s https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/ubol-filters.txt
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/badware.min.txt
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/privacy.min.txt
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.min.txt
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/unbreak.min.txt
            # curl -s https://ublockorigin.github.io/uAssetsCDN/filters/annoyances.min.txt
            } | sed 's/!#if env_safari/!#if (adguard_app_ios || adguard_ext_android_cb || adguard_ext_safari || adguard_ext_chromium_mv3)/g' | sed 's/!#if !ext_ubol/!#if (!adguard_app_ios \&\& !adguard_ext_android_cb \&\& !adguard_ext_safari \&\& !adguard_ext_chromium_mv3)/g' | grep -v '!#include' > ./optimized/ublock.txt 

      - name: Build CNAMEs
        run: |            
          {
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_dataunlocker.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_a8net.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_plausible.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_tracedock.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_at-internet.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_adobe.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_acton.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_otto.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_commanders-act.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_ingenious-technologies.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_np6.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_criteo.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_oracle.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_ad-ebis.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_eulerian.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_keyade.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_lead-forensics.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_webtrekk.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_wizaly.txt
            curl -s https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_cname_branch.txt
              } > ./optimized/cname.txt

      - name: Build Quick Fixes Filter
        run: TLS=insecure node src/cli.js -c examples/quickfix/configuration.json -o ./optimized/quickfix_optimized.txt

      - name: Push to repository
        run: |
          git config --global user.name "pkrayzy"
          git config --global user.email "pkrayzy@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Update Filters on $now"
          git push
