name: Build Filters

on:
  schedule:
  - cron: "0 3 * * *"
  # For manual run builds
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Extract and transform OISD Excludes
        run: |
          curl -s https://oisd.nl/excludes.php | grep -Eo '>([^<]+)<' | sed 's/>/@@||/; s/</^/' > OISD_Excludes.txt
          
      - name: Build DNS Filter
        run: TLS=insecure node src/cli.js -c examples/sdn/configuration.json -o filter.txt

      - name: Build Allowlist
        run: TLS=insecure node src/cli.js -c examples/whitelist/configuration.json -o whitelist.txt

      - name: Push to repository
        run: |
          git config --global user.name "pkrayzy"
          git config --global user.email "pkrayzy@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Update Filters on $now"
          git push