name: Build Quick Fixes

on:
  workflow_run:
    workflows: ["Download Filters"]
    types:
      - completed
  # For manual run builds
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Build Quick Fixes Filter
        run: TLS=insecure node src/cli.js -c examples/quickfix/configuration.json -o ./optimized/quickfix_optimized.txt

      - name: Push to repository
        run: |
          git config --global user.name "pkrayzy"
          git config --global user.email "pkrayzy@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Update Filters on $now"
          git push
